TestApp/Controllers/DatosContactosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Entities;
using TestApp.Models;

namespace TestApp.Controllers
{
    public class DatosContactosController : Controller
    {
        private TestAppContext db = new TestAppContext();

        // GET: DatosContactos
        public ActionResult Index()
        {
            var datosContactoes = db.DatosContactoes.Include(d => d.DatosPersonales);
            return View(datosContactoes.ToList());
        }

        // GET: DatosContactos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DatosContacto datosContacto = db.DatosContactoes.Find(id);
            if (datosContacto == null)
            {
                return HttpNotFound();
            }
            return View(datosContacto);
        }

        // GET: DatosContactos/Create
        //public ActionResult Create()
        //{
        //    ViewBag.DatosPersonalesId = new SelectList(db.DatosPersonales, "Id", "Nombre");
        //    return View();
        //}

        // GET: Credits/Create
        public ActionResult Create(int? id)
        {
            var Id = Convert.ToInt32(id);

            

            

            DatosContacto model = new DatosContacto();
            model.DatosPersonalesId = Id;

            return View(model);
        }
        // POST: DatosContactos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Telefono,Correo,DatosPersonalesId")] DatosContacto datosContacto)
        {
            if (ModelState.IsValid)
            {
                db.DatosContactoes.Add(datosContacto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DatosPersonalesId = new SelectList(db.DatosPersonales, "Id", "Nombre", datosContacto.DatosPersonalesId);
            return View(datosContacto);
        }

        // GET: DatosContactos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DatosContacto datosContacto = db.DatosContactoes.Find(id);
            if (datosContacto == null)
            {
                return HttpNotFound();
            }
            ViewBag.DatosPersonalesId = new SelectList(db.DatosPersonales, "Id", "Nombre", datosContacto.DatosPersonalesId);
            return View(datosContacto);
        }

        // POST: DatosContactos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Telefono,Correo,DatosPersonalesId")] DatosContacto datosContacto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(datosContacto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DatosPersonalesId = new SelectList(db.DatosPersonales, "Id", "Nombre", datosContacto.DatosPersonalesId);
            return View(datosContacto);
        }

        // GET: DatosContactos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DatosContacto datosContacto = db.DatosContactoes.Find(id);
            if (datosContacto == null)
            {
                return HttpNotFound();
            }
            return View(datosContacto);
        }

        // POST: DatosContactos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DatosContacto datosContacto = db.DatosContactoes.Find(id);
            db.DatosContactoes.Remove(datosContacto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TestApp/Controllers/DatosPersonalesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Entities;
using TestApp.Models;

namespace TestApp.Controllers
{
    public class DatosPersonalesController : Controller
    {
        private TestAppContext db = new TestAppContext();

        // GET: DatosPersonales
        public ActionResult Index()
        {
            var datosPersonales = db.DatosPersonales.Include(d => d.Estado);
            return View(datosPersonales.ToList());
        }

        // GET: DatosPersonales/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DatosPersonales datosPersonales = db.DatosPersonales.Find(id);
            if (datosPersonales == null)
            {
                return HttpNotFound();
            }
            return View(datosPersonales);
        }

        // GET: DatosPersonales/Create
        public ActionResult Create()
        {
            ViewBag.EstadoId = new SelectList(db.Estadoes, "Id", "Nombre");
            return View();
        }

        // POST: DatosPersonales/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nombre,ApellidoPaterno,ApellidoMaterno,Direccion,EstadoId,Activo")] DatosPersonales datosPersonales)
        {
            if (ModelState.IsValid)
            {
                db.DatosPersonales.Add(datosPersonales);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EstadoId = new SelectList(db.Estadoes, "Id", "Nombre", datosPersonales.EstadoId);
            return View(datosPersonales);
        }

        // GET: DatosPersonales/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DatosPersonales datosPersonales = db.DatosPersonales.Find(id);
            if (datosPersonales == null)
            {
                return HttpNotFound();
            }
            ViewBag.EstadoId = new SelectList(db.Estadoes, "Id", "Nombre", datosPersonales.EstadoId);
            return View(datosPersonales);
        }

        // POST: DatosPersonales/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nombre,ApellidoPaterno,ApellidoMaterno,Direccion,EstadoId,Activo")] DatosPersonales datosPersonales)
        {
            if (ModelState.IsValid)
            {
                db.Entry(datosPersonales).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EstadoId = new SelectList(db.Estadoes, "Id", "Nombre", datosPersonales.EstadoId);
            return View(datosPersonales);
        }

        // GET: DatosPersonales/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DatosPersonales datosPersonales = db.DatosPersonales.Find(id);
            if (datosPersonales == null)
            {
                return HttpNotFound();
            }
            return View(datosPersonales);
        }

        // POST: DatosPersonales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DatosPersonales datosPersonales = db.DatosPersonales.Find(id);
            db.DatosPersonales.Remove(datosPersonales);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TestApp/Views/DatosContactos/Create.cshtml
@model Entities.DatosContacto

@{
    ViewBag.Title = "Create";
}

<h2>Crear</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Datos de Contacto</h4>
        <hr />

        @Html.HiddenFor(model => model.DatosPersonalesId)

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })



        




        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Correo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Correo, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la Lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TestApp/Views/DatosContactos/Delete.cshtml
@model Entities.DatosContacto

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DatosContacto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DatosPersonales.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatosPersonales.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Correo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Correo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TestApp/Views/DatosContactos/Details.cshtml
@model Entities.DatosContacto

@{
    ViewBag.Title = "Details";
}

<h2>Detalles</h2>

<div>
    <h4>Datos Contacto GitHub</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DatosPersonales.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatosPersonales.Nombre)
            @Html.DisplayFor(model => model.DatosPersonales.ApellidoPaterno)
            @Html.DisplayFor(model => model.DatosPersonales.ApellidoMaterno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatosPersonales.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatosPersonales.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatosPersonales.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatosPersonales.Estado.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DatosPersonales.Activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatosPersonales.Activo)
        </dd>



        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Correo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Correo)
        </dd>

    </dl>
</div>
<p>
        <a href="~/DatosPersonales/Edit/@Model.Id" >Editar Datos Personales</a> |
        @*@Html.ActionLink("Desactivar", "Edit", "DatosPersonales", new { id = Model.Id }) |*@
        @Html.ActionLink("Regresar a la Lista", "Index")
</p>

TestApp/Views/DatosContactos/Edit.cshtml
@model Entities.DatosContacto

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Datos de Contacto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Correo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Correo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatosPersonalesId, "DatosPersonales", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DatosPersonalesId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DatosPersonalesId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la Lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TestApp/Views/DatosContactos/Index.cshtml
@model IEnumerable<Entities.DatosContacto>

@{
    ViewBag.Title = "Index";
}

<h2>Index cambios master </h2>

<p>
    @Html.ActionLink("Crear Nuevo","Create","DatosPersonales") | 
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DatosPersonales.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DatosPersonales.Direccion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DatosPersonales.Estado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DatosPersonales.Activo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefono)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Correo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        @{
            var color = "#fff";
            if (item.DatosPersonales.Activo == false)
            {
                color = "tomato";
            }
            else if (item.DatosPersonales.Activo == true)
            {
                color = "lightgreen";
            }


        }
        <td style="background-color:@color">
            @Html.DisplayFor(modelItem => item.DatosPersonales.Nombre)
            @Html.DisplayFor(modelItem => item.DatosPersonales.ApellidoPaterno)
            @Html.DisplayFor(modelItem => item.DatosPersonales.ApellidoMaterno)

        </td>
        <td style="background-color:@color">
            @Html.DisplayFor(modelItem => item.DatosPersonales.Direccion)
        </td>
        <td style="background-color:@color">
            @Html.DisplayFor(modelItem => item.DatosPersonales.Estado.Nombre)

        </td>
        <td style="background-color:@color">
            @Html.DisplayFor(modelItem => item.DatosPersonales.Activo)

        </td>

        <td style="background-color:@color">
            @Html.DisplayFor(modelItem => item.Telefono)
        </td>
        <td style="background-color:@color">
            @Html.DisplayFor(modelItem => item.Correo)
        </td>
        <td>
            @Html.ActionLink("Editar Datos de Contacto", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Detalles", "Details", new { id = item.Id }) |
            @*@Html.ActionLink("D", "Delete", new { id = item.Id })*@
        </td>
       



    </tr>
}

</table>