TestApp/Controllers/DatosContactosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Entities;
using TestApp.Models;

namespace TestApp.Controllers
{
    public class DatosContactosController : Controller
    {
        private TestAppContext db = new TestAppContext();

        // GET: DatosContactos
        public ActionResult Index()
        {
            var datosContactoes = db.DatosContactoes.Include(d => d.DatosPersonales);
            return View(datosContactoes.ToList());
        }

        // GET: DatosContactos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DatosContacto datosContacto = db.DatosContactoes.Find(id);
            if (datosContacto == null)
            {
                return HttpNotFound();
            }
            return View(datosContacto);
        }

        // GET: DatosContactos/Create
        //public ActionResult Create()
        //{
        //    ViewBag.DatosPersonalesId = new SelectList(db.DatosPersonales, "Id", "Nombre");
        //    return View();
        //}

        // GET: Credits/Create
        public ActionResult Create(int? id)
        {
            var Id = Convert.ToInt32(id);

            

            

            DatosContacto model = new DatosContacto();
            model.DatosPersonalesId = Id;

            return View(model);
        }
        // POST: DatosContactos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Telefono,Correo,DatosPersonalesId")] DatosContacto datosContacto)
        {
            if (ModelState.IsValid)
            {
                db.DatosContactoes.Add(datosContacto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DatosPersonalesId = new SelectList(db.DatosPersonales, "Id", "Nombre", datosContacto.DatosPersonalesId);
            return View(datosContacto);
        }

        // GET: DatosContactos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DatosContacto datosContacto = db.DatosContactoes.Find(id);
            if (datosContacto == null)
            {
                return HttpNotFound();
            }
            ViewBag.DatosPersonalesId = new SelectList(db.DatosPersonales, "Id", "Nombre", datosContacto.DatosPersonalesId);
            return View(datosContacto);
        }

        // POST: DatosContactos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Telefono,Correo,DatosPersonalesId")] DatosContacto datosContacto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(datosContacto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DatosPersonalesId = new SelectList(db.DatosPersonales, "Id", "Nombre", datosContacto.DatosPersonalesId);
            return View(datosContacto);
        }

        // GET: DatosContactos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DatosContacto datosContacto = db.DatosContactoes.Find(id);
            if (datosContacto == null)
            {
                return HttpNotFound();
            }
            return View(datosContacto);
        }

        // POST: DatosContactos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DatosContacto datosContacto = db.DatosContactoes.Find(id);
            db.DatosContactoes.Remove(datosContacto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TestApp/Controllers/DatosPersonalesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Entities;
using TestApp.Models;

namespace TestApp.Controllers
{
    public class DatosPersonalesController : Controller
    {
        private TestAppContext db = new TestAppContext();

        // GET: DatosPersonales
        public ActionResult Index()
        {
            var datosPersonales = db.DatosPersonales.Include(d => d.Estado);
            return View(datosPersonales.ToList());
        }

        // GET: DatosPersonales/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DatosPersonales datosPersonales = db.DatosPersonales.Find(id);
            if (datosPersonales == null)
            {
                return HttpNotFound();
            }
            return View(datosPersonales);
        }

        // GET: DatosPersonales/Create
        public ActionResult Create()
        {
            ViewBag.EstadoId = new SelectList(db.Estadoes, "Id", "Nombre");
            return View();
        }

        // POST: DatosPersonales/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nombre,ApellidoPaterno,ApellidoMaterno,Direccion,EstadoId,Activo")] DatosPersonales datosPersonales)
        {
            if (ModelState.IsValid)
            {
                db.DatosPersonales.Add(datosPersonales);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EstadoId = new SelectList(db.Estadoes, "Id", "Nombre", datosPersonales.EstadoId);
            return View(datosPersonales);
        }

        // GET: DatosPersonales/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DatosPersonales datosPersonales = db.DatosPersonales.Find(id);
            if (datosPersonales == null)
            {
                return HttpNotFound();
            }
            ViewBag.EstadoId = new SelectList(db.Estadoes, "Id", "Nombre", datosPersonales.EstadoId);
            return View(datosPersonales);
        }

        // POST: DatosPersonales/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nombre,ApellidoPaterno,ApellidoMaterno,Direccion,EstadoId,Activo")] DatosPersonales datosPersonales)
        {
            if (ModelState.IsValid)
            {
                db.Entry(datosPersonales).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EstadoId = new SelectList(db.Estadoes, "Id", "Nombre", datosPersonales.EstadoId);
            return View(datosPersonales);
        }

        // GET: DatosPersonales/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DatosPersonales datosPersonales = db.DatosPersonales.Find(id);
            if (datosPersonales == null)
            {
                return HttpNotFound();
            }
            return View(datosPersonales);
        }

        // POST: DatosPersonales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DatosPersonales datosPersonales = db.DatosPersonales.Find(id);
            db.DatosPersonales.Remove(datosPersonales);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TestApp/Views/DatosPersonales/Create.cshtml
@model Entities.DatosPersonales

@{
    ViewBag.Title = "Create";
}

<h2>Crear</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Datos Personales</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApellidoPaterno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApellidoPaterno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApellidoPaterno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApellidoMaterno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApellidoMaterno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApellidoMaterno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EstadoId, "Estado", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EstadoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EstadoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Activo)
                    @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TestApp/Views/DatosPersonales/Delete.cshtml
@model Entities.DatosPersonales

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DatosPersonales</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Estado.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApellidoPaterno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApellidoPaterno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApellidoMaterno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApellidoMaterno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TestApp/Views/DatosPersonales/Details.cshtml
@model Entities.DatosPersonales

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>DatosPersonales</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Estado.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApellidoPaterno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApellidoPaterno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApellidoMaterno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApellidoMaterno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TestApp/Views/DatosPersonales/Edit.cshtml
@model Entities.DatosPersonales

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DatosPersonales</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApellidoPaterno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApellidoPaterno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApellidoPaterno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApellidoMaterno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApellidoMaterno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApellidoMaterno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EstadoId, "EstadoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EstadoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EstadoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Activo)
                    @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la Lista", "Index","DatosContactos")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TestApp/Views/DatosPersonales/Index.cshtml
@model IEnumerable<Entities.DatosPersonales>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Crear Nuevo", "Create") |
    <a href="~/DatosContactos/Index/">
        Datos de Contacto
    </a>
</p>
<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApellidoPaterno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApellidoMaterno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Direccion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estado.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Activo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ApellidoPaterno)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ApellidoMaterno)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Direccion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estado.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Activo)
        </td>
        <td>
            @Html.ActionLink("Editar Datos Personales", "Edit", new { id=item.Id }) |
            
            @Html.ActionLink("Eliminar", "Delete", new { id = item.Id }) |

            @*@Html.ActionLink("Agregar Datos de Contacto", "Create","DatosContactos", new { id = item.Id })*@
            <a href="~/DatosContactos/Create/@item.Id" >
                Datos de Contacto
            </a>

        </td>
        @*<td>
            <a href="~/DatosContactos/Create/@item.Id" class="btn btn-primary" >
                <i class="fa fa-credit-card-alt" aria-hidden="true" title="Datos Contacto">Datos de Contacto</i>
            </a>
        </td>*@
    </tr>
}

</table>